### ISSUE TITLE
awsipranges: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dubrowin** [cmlccie/awsipranges#20]
I've tried to install awsipranges on both Ubuntu and Amazon Linux 2023 on new EC2 instances and after running the installation script: 

```curl --proto '=https' --tlsv1.2 -LsSf https://github.com/cmlccie/awsipranges/releases/download/v0.6.1/awsipranges-installer.sh | sh```

and setting the environment:

```source $HOME/.cargo/env```

both instances give me this error:

```awsipranges: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory```

**Comment by cmlccie** [comment]
@dubrowin , thank you for reporting this. I'll try and reproduce this issue this evening and get to the bottom of what is going on here.

**Comment by cmlccie** [comment]
Installing `v0.7.0` should fix this issue for you.

It looks like the Ubuntu and Amazon Linux AMIs have a more recent versions of OpenSSL installed. `awsipranges` `v0.6.1` was linked against OpenSSL v1.1, which isn't installed in these AMIs.

_Ubuntu:_
```bash
ubuntu@ip-172-31-43-195:~$ openssl version
OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024)
```

_Amazon Linux 2023:_
```bash
[ec2-user@ip-172-31-39-16 ~]$ openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
```

I could instruct users to ensure they have OpenSSL v1.1 installed on their systems, but this seems like a needless pain. We need TLS support to securely download the `ip-ranges.json` file, and that's it. We really don't need any other functionality from OpenSSL. I'd rather remove this dynamically linked dependency, and I'd rather not statically link OpenSSL. So, I opted to use [rultls](https://github.com/rustls/rustls) to provide the TLS functionality.

This ☝️ has the added benefit of allowing the tool to be more easily supported on Musl Linux and arm64 (AArch64) platforms - though binaries for these additional platforms will have to be built from source (today).

With version `v0.7.0`, you shouldn't have any issue installing and using `awsipranges` on amd64 instances running Ubuntu or Amazon Linux 2023 - I tested it on both. 😎

```bash
   ,     #_
   ~\_  ####_        Amazon Linux 2023
  ~~  \_#####\
  ~~     \###|
  ~~       \#/ ___   https://aws.amazon.com/linux/amazon-linux-2023
   ~~       V~' '->
    ~~~         /
      ~~._.   _/
         _/ _/
       _/m/'
[ec2-user@ip-172-31-39-16 ~]$ curl --proto '=https' --tlsv1.2 -LsSf https://github.com/cmlccie/awsipranges/releases/download/v0.7.0/awsipranges-installer.sh | sh
downloading awsipranges 0.7.0 x86_64-unknown-linux-gnu
installing to /home/ec2-user/.cargo/bin
  awsipranges
everything's installed!

To add $HOME/.cargo/bin to your PATH, either restart your shell or run:

    source $HOME/.cargo/env (sh, bash, zsh)
    source $HOME/.cargo/env.fish (fish)
[ec2-user@ip-172-31-39-16 ~]$ source $HOME/.cargo/env
[ec2-user@ip-172-31-39-16 ~]$ which awsipranges
~/.cargo/bin/awsipranges
[ec2-user@ip-172-31-39-16 ~]$ awsipranges -r us-west-2 -s s3
╭─────────────────────┬───────────┬──────────────────────┬─────────────────╮
│           IP Prefix ┆ Region    ┆ Network Border Group ┆ Services        │
╞═════════════════════╪═══════════╪══════════════════════╪═════════════════╡
│         3.5.76.0/22 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, EC2, S3 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│         3.5.80.0/21 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, EC2, S3 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│       18.34.48.0/20 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, EC2, S3 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│      18.34.244.0/22 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, EC2, S3 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│     35.80.36.208/28 ┆ us-west-2 ┆ us-west-2            ┆ S3              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│     35.80.36.224/28 ┆ us-west-2 ┆ us-west-2            ┆ S3              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│      52.92.128.0/17 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, S3      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│     52.218.128.0/17 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, S3      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2600:1f68:4000::/39 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, EC2, S3 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2600:1fa0:4000::/39 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, S3      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2600:1ff0:4000::/39 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, EC2, S3 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2600:1ff8:4000::/40 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, S3      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2600:1ff9:4000::/40 ┆ us-west-2 ┆ us-west-2            ┆ S3              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2600:1ffa:4000::/40 ┆ us-west-2 ┆ us-west-2            ┆ AMAZON, S3      │
╰─────────────────────┴───────────┴──────────────────────┴─────────────────╯
 14  AWS IP Prefixes  Data File Created  2024-08-06 23:53:09 UTC
  1  AWS Region              Sync Token  1722988389
```

**Comment by dubrowin** [comment]
Thanks! That worked. Great tool. I actually tried on ARM first and that failed. So when that's ready, I'd love to utilize that.

**Comment by cmlccie** [comment]
Yes, me too. 😎 I develop locally using macOS on Apple silicon, and I prefer to keep the CPU architecture (AArch64) consistent when deploying and working in AWS - plus it's cheaper! Today, you can install (build) from source on these platforms, and that requires you to install the Rust toolchain. I recognize that isn't ideal, so I'll work on adding pre-built binaries for these platforms.

Today, there's an issue with the way `cargo-dist` (the build tool/framework I am using) configures the GitHub Actions build environment that makes it difficult to build the Linux Musl and AArch64 binaries. If I have the time, I may try and contribute the solution. There is a relatively easy way to do what is needed using runner selection and Docker containers, but I haven't investigated how difficult it will be to update `cargo-dist` to use the method.

**Comment by dubrowin** [comment]
I was able to follow your page's instructions and was able to compile on AWS EC2 Graviton and copy around to other Graviton instances. Working great. Thanks!

**Comment by cmlccie** [comment]
Thank you for letting me know. I appreciate you.
